In [2]:
# Transpose

import numpy as np


In [3]:

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"


[[1 2]
 [3 4]]


In [4]:
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"


[[1 3]
 [2 4]]


In [5]:

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])


In [6]:
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"


[1 2 3]
[1 2 3]


In [16]:
e = np.random.random((3,2))
print(e)
e.shape

[[0.29637936 0.36009949]
 [0.80748022 0.31042664]
 [0.17839043 0.45759077]]


(3, 2)

In [17]:
aa = e.T
print(aa)
aa.shape

[[0.29637936 0.80748022 0.17839043]
 [0.36009949 0.31042664 0.45759077]]


(2, 3)